### ISSUE TITLE
How to stop ranchervm management server?

### ISSUE THREAD

**Issue by wlan0** [rancher/old-vm#12]
I started the server container using 

```
docker run --cap-add NET_ADMIN -v /var/run/docker.sock:/var/run/docker.sock -p 8080:80 rancher/vmmgmt:0.0.1
```

I can only stop it using `kill -9`

**Comment by ibuildthecloud** [comment]
@sheng-liang Can you exec the Python process in the startmgmt script?  This will make stop work better, but may cause issues with zombie.   If you get zombies the simplest fix is to run busybox init as PID 1

**Comment by sheng-liang** [comment]
We now exec the Python process. Kill -TERM now works.
