### ISSUE TITLE
No visual mode when booting an android4.4 image

### ISSUE THREAD

**Issue by jvassev** [rancher/old-vm#28]
Hi,
I tried preparing an Android x86 image following the instructions for windows. I use the iso from here: http://sourceforge.net/projects/android-x86/files/Release%204.4/android-x86-4.4-RC2.iso/download

While the vm boots in visual mode using virt-manager, when I start it from rancher-vm the vm/container starts in console mode immediately after grub is done.

**Comment by ibuildthecloud** [comment]
@sheng-liang I would guess there is no framebuffer defined in qemu.

**Comment by sheng-liang** [comment]
Since Android x86 does not support virtio drivers, you cannot use Windows image instructions. I have created a new image/android-x86 directory that contains Dockerfile, Makefile, and instructions. I was able to get Android x86 VMs created.
