### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by xavicampa** [rancher/old-vm#38]
It happens whenever I hit the web interface in port 8080 (blank screen is displayed in browser).

I'm running docker 1.6.1 in ubuntu 15.04 (physical). `kvm-ok` reports virtualization enabled. Started the container with your suggested command line:
`docker run -v /var/run/docker.sock:/var/run/docker.sock -p 8080:80 -v /tmp/ranchervm:/ranchervm rancher/ranchervm`

Startup log:

> WebSocket server settings:
> - Listen on :80
> - Flash security policy server
> - Web server. Web root: /var/lib/rancher/noVNC-0.0.2
> - SSL/TLS support
> - proxying from :80 to /ranchervm/vm
>   WARNING: no 'numpy' module, HyBi protocol will be slower

This is the whole exception stacktrace:

> 10.3.2.133 - - [12/May/2015 09:24:31] command: /var/lib/rancher/noVNC-0.0.2/cgi-bin/ranchervm ""
> 10.3.2.133 - - [12/May/2015 09:24:32] Traceback (most recent call last):
>   File "/var/lib/rancher/noVNC-0.0.2/cgi-bin/ranchervm", line 362, in <module>
>     [id for id in containers.keys()])),
>   File "/var/lib/rancher/noVNC-0.0.2/cgi-bin/ranchervm", line 360, in <lambda>
>     c.get("Config").get("Env")) != [],
> TypeError: 'NoneType' object is not iterable
> 
> 10.3.2.133 - - [12/May/2015 09:24:32] CGI script exit status 0x1

**Comment by sheng-liang** [comment]
This bug was actually fixed a week ago, but I neglected to publish a new image for ranchervm. Could you try again?

**Comment by xavicampa** [comment]
Went a bit further. Now it returns this when firing up the default vm:

> 172.16.99.124 - - [12/May/2015 21:09:19] command: /var/lib/rancher/noVNC-0.0.2/cgi-bin/ranchervm
> 172.16.99.124 - - [12/May/2015 21:09:19] Traceback (most recent call last):
>   File "/var/lib/rancher/noVNC-0.0.2/cgi-bin/ranchervm", line 303, in <module>
>     volumes_from = get_my_id())
>   File "/var/lib/rancher/noVNC-0.0.2/cgi-bin/ranchervm", line 240, in get_my_id
>     cgroup_file.read())[0][13:]
> IndexError: list index out of range
> 
> 172.16.99.124 - - [12/May/2015 21:09:19] CGI script exit status 0x1

And a blank screen appears in the browser. Going back to the list of instances, shows a new instance, with Start and Delete option. Clicking Start then returns:

> 172.16.99.124 - - [12/May/2015 21:10:55] command: /var/lib/rancher/noVNC-0.0.2/cgi-bin/ranchervm
> 172.16.99.124 - - [12/May/2015 21:10:55] Traceback (most recent call last):
>   File "/var/lib/rancher/noVNC-0.0.2/cgi-bin/ranchervm", line 332, in <module>
>     port_mappings = {x: txform(port_bindings.get(x)) for x in port_bindings}
> TypeError: 'NoneType' object is not iterable
> 
> 172.16.99.124 - - [12/May/2015 21:10:55] CGI script exit status 0x1

**Comment by sheng-liang** [comment]
Could you try: docker exec -it ranchervm_container_name cat /proc/self/cgroup and see the output?

**Comment by xavicampa** [comment]
This is it:

> 10:memory:/system.slice/docker-737714833ab59817e1c855c427f5e7008b13caf942935126f2463a54e334c41e.scope
> 9:hugetlb:/
> 8:devices:/system.slice/docker-737714833ab59817e1c855c427f5e7008b13caf942935126f2463a54e334c41e.scope
> 7:cpuset:/system.slice/docker-737714833ab59817e1c855c427f5e7008b13caf942935126f2463a54e334c41e.scope
> 6:perf_event:/
> 5:net_cls,net_prio:/
> 4:blkio:/system.slice/docker-737714833ab59817e1c855c427f5e7008b13caf942935126f2463a54e334c41e.scope
> 3:freezer:/system.slice/docker-737714833ab59817e1c855c427f5e7008b13caf942935126f2463a54e334c41e.scope
> 2:cpu,cpuacct:/system.slice/docker-737714833ab59817e1c855c427f5e7008b13caf942935126f2463a54e334c41e.scope
> 1:name=systemd:/system.slice/docker.service

**Comment by sheng-liang** [comment]
I see the content of this file changed between Ubuntu 14.04 and Ubuntu 15.04. I'll need to change the code to handle this.

**Comment by sheng-liang** [comment]
I checked in the fix and published new docker images. Could you give it a try?

**Comment by xavicampa** [comment]
Works now. Thanks!
