### ISSUE TITLE
Bridge vm / container to physical host interface?

### ISSUE THREAD

**Issue by pwFoo** [rancher/old-vm#52]
Is there a tutorial how to bridge a vm / container to a physical interface or add a second network interface? It isn't only rancher vm related, but that could be my first use case.

**Comment by sheng-liang** [comment]
I added instructions to bridge to the host interface: https://github.com/rancherio/vm/blob/master/docs/networking.md

It is possible to add a second network interface as well, however that requires adding a second interface into the container and changing the start script significantly. It is much more involved.

**Comment by pwFoo** [comment]
Hi @sheng-liang, thanks for instructions for bridged network! 
It sounds additional interface is to complex. 

My server have 3 network cards. That's why it would be interesting to bridge container / vm container to the second hardware interface instead of eth0. But it looks like docker only handles one interface?

**Comment by sheng-liang** [comment]
Right. You can always manually program a second or third interface into a container, but Docker would not know anything about it.

**Comment by pwFoo** [comment]
I have no experience with container networking, so I have to google and read about how to do it.
Thanks for answering my questions here :)
