### ISSUE TITLE
Live migration for the ranchervm

### ISSUE THREAD

**Issue by lavvy** [rancher/old-vm#58]
I was just feeling that live migration feature should be added in the ranchervm manager or even the rancher server itself. since some people may want to use ranchervm as rancher hosts to run their application stack containers.
Thinking about it , create a service that will be spinning out virtual machine hosts for another application stack to be consuming the hosts as it scales. 
Then for maintenance purposes you will migrate the vm hosts to another physical hosts without interrupting the services in the application stacks.

**Comment by LLParse** [comment]
Live migration was added in v0.1.0
