### ISSUE TITLE
Could RancherVMs work with calico vRouter or weave vSwitch?

### ISSUE THREAD

**Issue by pwFoo** [rancher/old-vm#61]
Could it possible to build networks inside the RancherVM and work with inside the kvm VM?

https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/libnetwork/Demonstration.md

http://docs.weave.works/weave/latest_release/features.html#docker

**Comment by errordeveloper** [comment]
@pwFoo I cannot speak of Calico, but with respect to Weave Net it should be possible to do various things, it just depend on what you'd like to achieve. I think it'd be best to port to the mailing list, so other users might comment on this also. Additionally, please take a look at @davedoesdev [fold project](https://github.com/davedoesdev/fold), it does something quite similar.

**Comment by davedoesdev** [comment]
At some point I'm hoping to port Weave Net to [rumprun](https://github.com/rumpkernel/rumprun)

**Comment by davedoesdev** [comment]
At some point I'm going to port Weave Net to [rumprun](https://github.com/rumpkernel/rumprun) and combine it with [fold](https://github.com/davedoesdev/fold), for a Docker-free experience.
