### ISSUE TITLE
can't use the console 

### ISSUE THREAD

**Issue by xrain0610** [rancher/old-vm#66]
Hi,
I use the rancherVM , but when i created some instances, 
i can't find how to use console
<img width="1392" alt="2016-01-08 15 51 47" src="https://cloud.githubusercontent.com/assets/11401602/12193098/dea8d374-b61f-11e5-9adf-6a68d32d712e.png">

**Comment by JonathonReinhart** [comment]
The `Console` link appeared for my `rancher/vm-ubuntu` image, but not for my `rancher/vm-rancheros` image. I don't yet know how they detect it, but I'm guessing it has to do with one having VGA output and the other not.

I bet if you try starting that `vm-ubuntu` image, you'll see the console link.

**Comment by pwFoo** [comment]
No chance to login to vm-rancheros because ssh with password is disabled and no console available.

Is there a way / workaround to get RancherVM console working for vm-rancheros?

**Comment by JonathonReinhart** [comment]
Since @pwFoo opened #73 which is more specific, this should be closed as duplicate.

**Comment by pwFoo** [comment]
@JonathonReinhart 
Also take a look here! #70  
Image should be updated, but works!

**Comment by LLParse** [comment]
Closing due to age. The UI was rewritten and the console/novnc button is plainly visible.
