### ISSUE TITLE
Development discontinued?

### ISSUE THREAD

**Issue by pwFoo** [rancher/old-vm#86]
Is RancherVM development discontinued?

**Comment by pwFoo** [comment]
@yasker cc

**Comment by mharrend** [comment]
:+1: for this issue.
I would also like to know if this handy feature is getting further development since it would be very useful.

**Comment by sradvanski** [comment]
I would also be interested to know if development will be continued.
Also if not could you point us to a project that is maybe replacing this one.

Thanks a lot.

**Comment by buck-ross** [comment]
Is this project officially dead?

This looks absolutely amazing, but it doesn't look like any development has happened in years...

**Comment by LLParse** [comment]
@haximilian, et al. Development on this project resumed as of a week ago. 

RancherVM will soon run atop Rancher 2.0
 (or any Kubernetes 1.9+ cluster with nodes that have KVM installed). 

For the initial release, we will support VMs with bridge networking and a single root disk with no redundancy. Coming soon.

In future releases we plan to tackle snapshots/backups, data redundancy, intelligent scheduling, live migration, and more.

**Comment by buck-ross** [comment]
@LLParse Excellent! Looks like I happened upon it at precisely the right time, then.

Now to integrate this into Mesos.

**Comment by inorton** [comment]
Any example videos of use? I might find this useful at work!

**Comment by LLParse** [comment]
@inorton 
https://rancher.com/blog/2018/2018-04-27-ranchervm-now-available-on-kubernetes/
https://rancher.com/blog/2018/2018-05-30-ranchervm-live-migration/

Closing.
